version: 2.9.0
apkFileName: installer-65fda3e4.apk
isFrameworkApk: false
usesFramework:
  ids:
  - 1
  tag: null
sdkInfo:
  minSdkVersion: 21
  targetSdkVersion: 28
packageInfo:
  forcedPackageId: 127
  renameManifestPackage: null
versionInfo:
  versionCode: 5480
  versionName: 3.70
resourcesAreCompressed: false
sharedLibrary: false
sparseResources: false

