package ca.retha.drifting;
/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int ic_launcher = 0x7f020000;
        public static final int abc_acrobatical_precedaneous_tucking = 0x7f020001;
        public static final int abc_bardie_zephyrus_zoccolo = 0x7f020002;
        public static final int abc_chob_incornished_chelatable = 0x7f020003;
        public static final int abc_concluder = 0x7f020004;
        public static final int abc_fionnuala_quizzers_yellower = 0x7f020005;
        public static final int aphemic_zoogeographically = 0x7f020006;
        public static final int common_tradeoff = 0x7f020007;
        public static final int common_unattackableness = 0x7f020008;
        public static final int notification_amphirhine = 0x7f020009;
        public static final int notification_bacterioprecipitin_quinquagesima_odontophorous = 0x7f02000a;
        public static final int notification_bridgetree_tc_bestrewment = 0x7f02000b;
        public static final int notification_camponotus = 0x7f02000c;
        public static final int notification_colostric = 0x7f02000d;
        public static final int notification_connectivity_cordaitaceous = 0x7f02000e;
        public static final int notification_ferntickled_geophagy_nasaump = 0x7f02000f;
        public static final int notification_hydration = 0x7f020010;
        public static final int notification_ihi_jingling_noncommitted = 0x7f020011;
        public static final int notification_inconsistently_brailing_identification = 0x7f020012;
        public static final int notification_misquoter_plantator = 0x7f020013;
        public static final int notification_necessary_stercophagous = 0x7f020014;
        public static final int notification_vallancy = 0x7f020015;
        public static final int notification_victimising_proposed_transitmen = 0x7f020016;
        public static final int notification_zeuctocoelomata_honer_strainedly = 0x7f020017;
        public static final int plumification_crania_marcosian = 0x7f020018;
        public static final int podzolic_porterlike_ungnostic = 0x7f020019;
        public static final int tabber_cahiz_trihemimeris = 0x7f02001a;
        public static final int tonality_cichloid_perispherical = 0x7f02001b;
        public static final int underfinanced_reedman = 0x7f02001c;
        public static final int undisguised_entrec_lauans = 0x7f02001d;
        public static final int undisguised_expatiative_plower = 0x7f02001e;
        public static final int undisguised_peduncled = 0x7f02001f;
        public static final int undisguised_pentacetate_honkey_litter = 0x7f020020;
        public static final int undisguised_reoutfit_hyperacute = 0x7f020021;
        public static final int undisguised_sapajous = 0x7f020022;
        public static final int undisguised_tilefish_clupeine = 0x7f020023;
    }

    public static final class layout {
        public static final int activity_main = 0x7f030000;
        public static final int list = 0x7f030001;
    }

    public static final class color {
        public static final int colorAccent = 0x7f040000;
        public static final int colorPrimary = 0x7f040001;
        public static final int colorAppTheme = 0x7f040002;
        public static final int colorPrimaryDark = 0x7f040003;
        public static final int colorTextPrimary = 0x7f040004;
        public static final int colorTextSecondly = 0x7f040005;
        public static final int colorGray = 0x7f040006;
        public static final int colorSharpGreen = 0x7f040007;
        public static final int colorTextGray = 0x7f040008;
        public static final int colorControlHighlight = 0x7f040009;
        public static final int colorControlNormal = 0x7f04000a;
        public static final int aimbot_button_background = 0x7f04000b;
        public static final int aimbot_button_background_hover_moving = 0x7f04000c;
        public static final int aimbot_button_off = 0x7f04000d;
        public static final int aimbot_button_on = 0x7f04000e;
        public static final int aimbot_button_tint_hover_moving = 0x7f04000f;
        public static final int aimbot_start_position_cross = 0x7f040010;
        public static final int bg_fwind_swipe_bounds = 0x7f040011;
        public static final int black = 0x7f040012;
        public static final int sky_blue = 0x7f040013;
        public static final int blue_to_start = 0x7f040014;
        public static final int daemon_running = 0x7f040015;
        public static final int daemon_stopped = 0x7f040016;
        public static final int editor_color_cyan = 0x7f040017;
        public static final int editor_color_green = 0x7f040018;
        public static final int editor_color_pink = 0x7f040019;
        public static final int editor_color_red = 0x7f04001a;
        public static final int editor_color_white = 0x7f04001b;
        public static final int editor_color_yellow = 0x7f04001c;
        public static final int error_color_material_dark = 0x7f04001d;
        public static final int fg_aimbot_button_off = 0x7f04001e;
        public static final int fg_aimbot_button_on = 0x7f04001f;
        public static final int fwind_main_tab_bg = 0x7f040020;
        public static final int gm2_colorAccent = 0x7f040021;
        public static final int gm2_colorPrimary = 0x7f040022;
        public static final int gm2_colorPrimaryDark = 0x7f040023;
        public static final int gray_container = 0x7f040024;
        public static final int green_bg = 0x7f040025;
        public static final int green_fg = 0x7f040026;
        public static final int horizontal_dividing_line = 0x7f040027;
        public static final int ic_gm2_background = 0x7f040028;
        public static final int indigo_bg = 0x7f040029;
        public static final int indigo_fg = 0x7f04002a;
        public static final int kill_button_light_white = 0x7f04002b;
        public static final int logout_red = 0x7f04002c;
        public static final int notification_action_color_filter = 0x7f04002d;
        public static final int notification_icon_bg_color = 0x7f04002e;
        public static final int notification_material_background_media_default_color = 0x7f04002f;
        public static final int primary_text_default_material_dark = 0x7f040030;
        public static final int purple_bg = 0x7f040031;
        public static final int purple_fg = 0x7f040032;
        public static final int radar_safe = 0x7f040033;
        public static final int radar_unsafe = 0x7f040034;
        public static final int red_bg = 0x7f040035;
        public static final int red_fg = 0x7f040036;
        public static final int red_to_stop = 0x7f040037;
        public static final int ripple_material_light = 0x7f040038;
        public static final int secondary_text_default_material_dark = 0x7f040039;
        public static final int secondary_text_default_material_light = 0x7f04003a;
        public static final int selectable_activated_blue = 0x7f04003b;
        public static final int selectable_hover_gray = 0x7f04003c;
        public static final int ss_login_disabled = 0x7f04003d;
        public static final int ss_login_enabled = 0x7f04003e;
        public static final int transparent = 0x7f04003f;
        public static final int white = 0x7f040040;
        public static final int yellow_bg = 0x7f040041;
        public static final int yellow_fg = 0x7f040042;
    }

    public static final class style {
        public static final int AppTheme = 0x7f050000;
        public static final int FullScreen = 0x7f050001;
        public static final int NoActionBar = 0x7f050002;
        public static final int NoStatusBar = 0x7f050003;
        public static final int Gm2Theme = 0x7f050004;
    }

    public static final class id {
        public static final int header1 = 0x7f060000;
        public static final int new_layout = 0x7f060001;
        public static final int goto_site_button = 0x7f060002;
        public static final int refresh_button = 0x7f060003;
        public static final int anouncement_layout = 0x7f060004;
        public static final int update_layout = 0x7f060005;
        public static final int update_title = 0x7f060006;
        public static final int update_summary = 0x7f060007;
        public static final int anouncement_layout2 = 0x7f060008;
        public static final int anouncement_title = 0x7f060009;
        public static final int anouncement_summary = 0x7f06000a;
        public static final int anouncement_more = 0x7f06000b;
        public static final int instruction_layout = 0x7f06000c;
        public static final int progressBar1 = 0x7f06000d;
        public static final int header2 = 0x7f06000e;
        public static final int retry_txt = 0x7f06000f;
        public static final int listview1 = 0x7f060010;
        public static final int listbg = 0x7f060011;
        public static final int listTitle = 0x7f060012;
        public static final int listIsInstalled = 0x7f060013;
        public static final int listStatus = 0x7f060014;
    }
}
